export const SEARCH_PELIS = "SEARCH_PELIS";
export const FILTER_DURATION = "FILTER_DURATION";
export const ORDER_DATE = "ORDER_DATE";
export const SIGN_IN_SIGN_OUT = "SIGN_IN_SIGN_OUT";

//ACA VAN TODAS LAS ACTION TYPES
