export const SEARCH_PELIS = "SEARCH_PELIS";
export const FILTER_DURATION = "FILTER_DURATION";
export const ORDER_DATE = "ORDER_DATE";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const ORDER_COMMENT = "ORDER_COMMENT";
export const GET_MOVIES = "GET_MOVIES";
export const GET_GENRES = "GET_GENRES";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const FILTER_MOVIES_BY_COUNTRY = "FILTER_MOVIES_BY_COUNTRY";
export const FILTER_MOVIES_BY_GENRE = "FILTER_MOVIES_BY_GENRE";
export const ORDER_BY_RATING = "ORDER_BY_RATING";
export const MOVIE_DETAIL = "MOVIE_DETAIL";
export const SIGN_UP_USER = "SIGN_UP_USER";
//ACA VAN TODAS LAS ACTION TYPES
